version: "3.5"

services:
  project:
    build:
      target: project-image
      args:
        - PIP_USERNAME
        - PIP_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "127.0.0.1:5064:5064"
    environment:
      - HOST=0.0.0.0
      - PORT=5064
      - RDS_DB_URI=${RDS_DB_URI:-postgresql://postgres:pilot5kX8@postgres:5432/project}
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    ports:
      - "127.0.0.1:6432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-project}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pilot5kX8}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  alembic:
    build:
      target: alembic-image
      args:
        - PIP_USERNAME
        - PIP_PASSWORD
    environment:
      - RDS_DB_URI=${RDS_DB_URI:-postgresql://postgres:pilot5kX8@postgres:5432/project}
    volumes:
      - ./migrations/:/app/migrations/
      - ./project/:/app/project/
    depends_on:
      - postgres

volumes:
  postgres-data:
