version: "3"

services:
  app:
    build:
      context: .
      args:
        - REGISTRY_USERNAME
        - REGISTRY_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "127.0.0.1:5064:5064"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    ports:
      - "127.0.0.1:6432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-project}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pilot5kX8}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/scripts/:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
